config/routes.rb
Textbookswap::Application.routes.draw do

  match '/' => 'index#index', :as => :index
  get '/admin/courses/input/:term/:year' => 'courses#input', :as => :course_input
  get '/:transaction_type/course/show' => 'courses#show', :as => :show_courses
  post '/:transaction_type/course/find' => 'courses#find', :as => :find_course
  get '/:transaction_type/courses/:id/book/show' => 'courses#show_books', :as => :show_books
  get '/courses/:id/book/new' => 'books#display_new', :as => :display_new_book
  put '/courses/:id/book/new' => 'books#create_new', :as => :create_new_book
  get '/books/:book_id/posting/show' => 'books#show_postings', :as => :show_postings
  get '/books/:book_id/posting/new' => 'postings#display_new', :as => :display_new_posting
  put '/books/:book_id/posting/new' => 'postings#create_new', :as => :create_new_posting
  get '/postings/:posting_id' => 'postings#show', :as => :show_posting
  post '/postings/:posting_id' => 'postings#commit_buy', :as => :commit_buy_posting
  get '/course/find_course_numbers' => 'courses#find_course_numbers', :as => :find_course_numbers
  get '/course/find_course_sections' => 'courses#find_course_sections', :as => :find_course_sections
  get '/postings/admin/:unique_string' => 'postings#admin', :as => :display_admin_posting
  post '/postings/admin/:unique_string' => 'postings#commit_edit_and_republish', :as => :commit_admin_posting
  delete '/postings/delete/:unique_string' => 'postings#delete', :as => :delete_posting
  get '/admin' => 'misc#display', :as => :display_admin_page
  post '/admin' => 'misc#commit_edit', :as => :commit_admin_page_edit
  put '/admin/addnew' => 'users#new', :as => :new_user
  match '/auth/:provider/callback', :to => 'sessions#create', :as => :login
  match '/auth/failure', :to => 'sessions#failure'
  get '/logout', :to => 'sessions#destroy', :as => :logout
  
  get '/admin/fake_login' => 'users#fake_login', :as => :fake_login

end

app/models/posting.rb
class Posting < ActiveRecord::Base
	attr_accessible :seller_email, :seller_name, :price, :location, :condition, :comments
  belongs_to :book
  validates :seller_email, :price, :condition, :presence => true
	validates :seller_email, :email => true
	
  def send_seller_buyer_info(buyer_email, body, admin_link)
    UserMailer.send_seller_buyer_email(self.seller_email, buyer_email, body, Book.find_by_id(self.book_id).title, admin_link).deliver
	end
	
	def self.encrypt(posting_id)
	  ((posting_id+10)**16).to_s(36)
	end
	
	def self.decrypt(cyphertext)
	  ((cyphertext.to_i(36)**(1.0/16))-10).to_i
	end
	
end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController

  def show
    @posting = Posting.find_by_id(params[:posting_id])
    if @posting.nil?
    	flash[:warning] = "The requested posting id does not exist"
      redirect_to index_path() and return
    end
    @book = @posting.book
  end

  def commit_buy
    if params[:email][:body] == ""
    	flash[:warning] = "Please fill in all the fields"
      redirect_to show_posting_path(params[:posting_id]) and return
    end
    if !params[:email][:buyer_email].match(/^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i)
    	flash[:warning] = "Please fill in the required fields"
    	redirect_to show_posting_path(params[:posting_id]) and return
    end
    post = Posting.find_by_id(params[:posting_id])
    if post.nil?
    	flash[:warning] = "Buy request failed because the given post id does not exist"
    	redirect_to index_path and return
    else
			post.send_seller_buyer_info(params[:email][:buyer_email], params[:email][:body], "textbookswap.herokuapp.com" + display_admin_posting_path(Posting.encrypt(post.id)))
			post.reserved = true
			post_reserved_success = post.save!
			if(post_reserved_success)
    		flash[:notice] = "Buy request submitted! We have emailed the seller your message & contact information!"
    		redirect_to index_path and return
    	else
    		flash[:warning] = "Buy request failed because of database error"
    		redirect_to index_path and return
    	end
    end
  end

  def display_new
    @book = Book.find_by_id(params[:book_id])
    if @book.nil?
    	flash[:warning] = "The given book id does not exist"
      redirect_to index_path and return
    end
  end

  def create_new
    book = Book.find_by_id(params[:book_id])
    if book.nil?
    	flash[:warning] = "Posting failed because the given book id does not exist"
      redirect_to index_path and return
    end
    if params[:posting][:seller_email] == ""
    	flash[:warning] = "Posting failed because you did not enter a valid email"
      redirect_to display_new_posting_path(params[:book_id]) and return
    end
    new_posting_attributes = params[:posting]
    new_posting_attributes[:book_id] = book.id
    new_posting = Posting.create(new_posting_attributes)
    new_posting.book_id = book.id
    new_posting.save
    if(new_posting.errors.empty?)
    	domain_name = "textbookswap.herokuapp.com"
    	UserMailer.send_seller_admin_page(new_posting.seller_email, domain_name + display_admin_posting_path(Posting.encrypt(new_posting.id)), new_posting.book.title).deliver
    	flash[:notice] = "Book posting submitted! We will e-mail you if someone wishes to buy your book!"
    	redirect_to index_path and return
    else
    	flash[:warning] = "Posting failed. Please fill in all the form data."
    	redirect_to display_new_posting_path(params[:book_id]) and return
    end
  end
  
  def admin
  	posting_id = Posting.decrypt(params[:unique_string])
  	@posting = Posting.find_by_id(posting_id)
  	if @posting.nil?
  		flash[:warning] = "The requested posting does not exist"
  		redirect_to index_path and return
  	end
  	@book = @posting.book
  end
  
  def commit_edit_and_republish
  	posting_id = Posting.decrypt(params[:unique_string])
  	posting = Posting.find_by_id(posting_id)
  	if posting.nil?
  		flash[:warning] = "The requested posting does not exist"
  		redirect_to index_path and return
  	end
  	posting.update_attributes(params[:new_post])
  	if(posting.errors.empty?)
  		posting.reserved = false
  		posting.save!
			flash[:notice] = "Your updated post has been republished!"
			redirect_to show_posting_path(posting_id)
  	else
  		flash[:warning] = "The update failed because some form fields are invalid"
  		redirect_to display_admin_posting_path(params[:unique_string])
  	end
  end
  
  def delete
  	posting_id = Posting.decrypt(params[:unique_string])
  	posting = Posting.find_by_id(posting_id)
  	if posting.nil?
  		flash[:warning] = "The requested posting does not exist"
  		redirect_to index_path and return
  	end
  	posting.destroy
  	flash[:notice] = "Post Successfully Deleted!"
  	redirect_to index_path
  end
end

app/helpers/postings_helper.rb
module PostingsHelper
end

app/views/postings/_email_form.html.haml
%h2 Contact the Seller

If you are interested in purchasing this book, please fill out this form and send an email to the seller.

= form_tag commit_buy_posting_path("#{@posting.id}"), :id => "buyer_info_form", :method => :post do

  %p
    = label :email, :buyer_email, 'Your e-mail:'
    = text_field :email, :buyer_email, :class => "required email"
  
  %p
    = label :email, :body, 'Message to the seller:'
    %br
    = text_area :email, :body, :size => "80x5", :class => "required"
    
  %p
    = submit_tag 'Send'
    

app/views/postings/admin.html.haml
%h2 Edit details about your posting for #{@book.title}

= form_tag commit_admin_posting_path("#{Posting.encrypt(@posting.id)}"), :id => "edit_posting_form", :method => :post do

  %p
    = label :new_post, :seller_email, 'Your e-mail:'
    %br
    = text_field :new_post, :seller_email, :class => "required email", :value => "#{@posting.seller_email}", :id => "posting_seller_email"

  %p
    = label :new_post, :seller_name, 'Your name:'
    %br
    = text_field :new_post, :seller_name, :value => "#{@posting.seller_name}", :id => "posting_seller_name"

  %p
    = label :new_post, :price, 'Price in dollars:'
    %br
    = text_field :new_post, :price, :class => "required integer_price", :value => "#{@posting.price}"
        
  %p
    = label :new_post, :condition, 'Condition of your book:'
    = select :new_post, :condition, ['Brand New', 'Used it few times', 'Notes all over'], :value => "#{@posting.condition}"
    
  %p
    = label :new_post, :location, 'Where you want to meet to sell your book:'
    = select :new_post, :location, ['North Side', 'South Side', 'West Side', 'East Side'], :value => "#{@posting.location}"
    
  %p
    = label :new_post, :comments, 'Miscellaneous comments:'
    %br
    = text_area :new_post, :comments, :size => "80x5", :value => "#{@posting.comments}"

  %p  
    = submit_tag 'Update and Re-Publish'


= button_to "Delete Post", delete_posting_path("#{Posting.encrypt(@posting.id)}"), :method => :delete, :id => "Delete Post", :confirm => 'Are you sure?'

app/views/postings/display_new.html.haml
%h2 Enter in  details about your posting

= form_tag create_new_posting_path("#{@book.id}"), :id => "create_posting_form", :method => :put do

  %p
    = label :posting, :seller_email, 'Your e-mail:'
    %br
    = text_field :posting, :seller_email, :class => "required email"

  %p
    = label :posting, :seller_name, 'Your name:'
    %br
    = text_field :posting, :seller_name

  %p
    = label :posting, :price, 'Price in dollars:'
    %br
    = text_field :posting, :price, :class => "required integer_price"
        
  %p
    = label :posting, :condition, 'Condition of your book:'
    = select :posting, :condition, ['Brand New', 'Used it few times', 'Notes all over']
    
  %p
    = label :posting, :location, 'Where you want to meet to sell your book:'
    = select :posting, :location, ['North Side', 'South Side', 'West Side', 'East Side']
    
  %p
    = label :posting, :comments, 'Miscellaneous comments:'
    %br
    = text_area :posting, :comments, :size => "80x5"

  %p
    = submit_tag 'Post!'
    

app/views/postings/show.html.haml
%div
	- if not session[:user_id].nil?
		#admin_delete
			= button_to "Delete This Post", delete_posting_path("#{Posting.encrypt(@posting.id)}"), :method => :delete, :id => "Delete This Post", :confirm => 'Are you sure?'

%h2 Posting Info for #{@book.title}

%p
	Contact e-mail:
	= @posting.seller_email
       
- if not @posting.seller_name == ""
	%p
		Contact name:
		= @posting.seller_name
    
%p
	Price:
	= @posting.price
  
%p
	Condition:
	= @posting.condition   

%p
	Posted on:
	= @posting.created_at
  
%p
	Preferred Meeting Location:
	= @posting.location

%p
	Comment:
	= @posting.comments
   
= render :partial => "postings/email_form"