config/routes.rb
Textbookswap::Application.routes.draw do

  match '/' => 'index#index', :as => :index
  get '/admin/courses/input/:term/:year' => 'courses#input', :as => :course_input
  get '/:transaction_type/course/show' => 'courses#show', :as => :show_courses
  post '/:transaction_type/course/find' => 'courses#find', :as => :find_course
  get '/:transaction_type/courses/:id/book/show' => 'courses#show_books', :as => :show_books
  get '/courses/:id/book/new' => 'books#display_new', :as => :display_new_book
  put '/courses/:id/book/new' => 'books#create_new', :as => :create_new_book
  get '/books/:book_id/posting/show' => 'books#show_postings', :as => :show_postings
  get '/books/:book_id/posting/new' => 'postings#display_new', :as => :display_new_posting
  put '/books/:book_id/posting/new' => 'postings#create_new', :as => :create_new_posting
  get '/postings/:posting_id' => 'postings#show', :as => :show_posting
  post '/postings/:posting_id' => 'postings#commit_buy', :as => :commit_buy_posting
  get '/course/find_course_numbers' => 'courses#find_course_numbers', :as => :find_course_numbers
  get '/course/find_course_sections' => 'courses#find_course_sections', :as => :find_course_sections
  get '/postings/admin/:unique_string' => 'postings#admin', :as => :display_admin_posting
  post '/postings/admin/:unique_string' => 'postings#commit_edit_and_republish', :as => :commit_admin_posting
  delete '/postings/delete/:unique_string' => 'postings#delete', :as => :delete_posting
  get '/admin' => 'misc#display', :as => :display_admin_page
  post '/admin' => 'misc#commit_edit', :as => :commit_admin_page_edit
  put '/admin/addnew' => 'users#new', :as => :new_user
  match '/auth/:provider/callback', :to => 'sessions#create', :as => :login
  match '/auth/failure', :to => 'sessions#failure'
  get '/logout', :to => 'sessions#destroy', :as => :logout
  
  get '/admin/fake_login' => 'users#fake_login', :as => :fake_login

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def show
    @transaction_type = params[:transaction_type]
    temp = Course.select("department_long")
    @departments = []
    temp.each do |dept|
      @departments << dept.department_long unless dept.department_long == "" or @departments.include?(dept.department_long)
    end
    temp = Course.select("number")
    @numbers = []
    temp.each do |num|
      @numbers << num.number unless num.number == "" or @numbers.include?(num.number)
    end
    temp = Course.select("section")
    @sections = []
    temp.each do |sec|
      @sections << sec.section unless sec.section == "" or @sections.include?(sec.section)
    end
    @departments.sort!
    @numbers.sort_by! do |s|
      [1, s.gsub(/[a-zA-Z]/, "").to_i]
    end
    @sections.sort!
  end

  def input
    Course.get_courses_for(params[:term], params[:year].to_i)
    redirect_to '/'
  end

  def find
    course_term = Misc.find_by_key("semester").value
    course_year = Misc.find_by_key("year").value.to_i
    if params[:course].nil?
      flash[:warning] = "No course was selected"
      redirect_to show_courses_path(params[:transaction_type]) and return
    end
    course = Course.find(:first, :conditions => { :term => course_term,
                           :year => course_year,
                           :department_long => params[:course][:department],
                           :number => params[:course][:number],
                           :section => params[:course][:section] } )
    if course.nil?
      flash[:warning] = "No course was found"
      redirect_to show_courses_path(params[:transaction_type]) and return
    end
    redirect_to show_books_path(params[:transaction_type], course.id)
  end

  def show_books
    @odd = true
    @course = Course.find_by_id(params[:id])
    @transaction_type = params[:transaction_type]

    @required_books, @unrequired_books = @course.find_required_and_unrequired_books

    if @required_books.empty?
      flash[:warning] = "This class has no required books"
    end

  end

  #returns json for ajax request from /:transaction_type/course/show
  def find_course_numbers
    department = params[:department]
    courses = Course.find_all_by_department_long(department)
    @numbers = []
    courses.each do |course|
      @numbers << course.number unless course.number == "" or @numbers.include?(course.number)
    end
    respond_to do |format|
      format.json { render :json => @numbers }
    end
  end

  #returns json for ajax request from /:transaction_type/course/show
  def find_course_sections
    department = params[:department]
    number = params[:number]
    courses = Course.find_all_by_department_long_and_number(department, number)
    @sections = []
    courses.each do |course|
      @sections << course.section unless course.section == "" or @sections.include?(course.section)
    end
    respond_to do |format|
      format.json { render :json => @sections }
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_book.html.haml
%li
  Title:
  - if @transaction_type == 'buy'
    = link_to "#{book.title}", show_postings_path(book.id)
  - else
    = link_to "#{book.title}", display_new_posting_path(book.id)

%li
  Author:
  = book.author
      
%li
  Edition:
  = book.edition

app/views/courses/_required.html.haml
%h2 Required Books

#Required

	- @required_books.each do |book|
	
		- if @odd == true
		
			%div.list.grey
			
				= render :partial => "courses/book", :locals => {:book => book}
				
			- @odd = false
			
		- else
		
			%div.list.darkgrey
			
				= render :partial => "courses/book", :locals => {:book => book}
				
			- @odd = true
      

app/views/courses/_unrequired.html.haml
%h2 Recommended Books

#Unrequired

	- @unrequired_books.each do |book|
	
		- if @odd == true
			
			%div.list.grey
			
				= render :partial => "courses/book", :locals => {:book => book}
				
			- @odd = false
			
		- else
		
			%div.list.darkgrey
			
				= render :partial => "courses/book", :locals => {:book => book}
				
			- @odd = true
      

app/views/courses/show.html.haml
- if @transaction_type == 'buy'
  %h2 Choose the class you are buying books for:
- else
  %h2 Choose the class you are selling books for:

= form_tag find_course_path("#{params[:transaction_type]}"), :method => :post do

  %p
    = label :course, :department, 'Department:'
    = select :course, :department, @departments

  %p
    = label :course, :number, 'Number:'
    = select :course, :number, @numbers

  %p
    = label :course, :section, 'Section:'
    = select :course, :section, @sections

  %p
    = submit_tag 'Go choose a book', :name => 'search'

app/views/courses/show_books.html.haml
%h2 Textbooks for #{@course.department_long} #{@course.number}

- if @transaction_type == 'buy'
  %p Click on a book to see the offers for that book.
- else
  %p Click on a book to create a posting for that book, if you don't see the book you are trying to sell listed, please click "Enter Unlisted Book"

= render :partial => "courses/required"

= render :partial => "courses/unrequired"

- if @transaction_type == 'sell'

  %br

  = button_to 'Enter Unlisted Book', display_new_book_path(@course), :action => "display_new", :method => :get