config/routes.rb
Textbookswap::Application.routes.draw do

  match '/' => 'index#index', :as => :index
  get '/admin/courses/input/:term/:year' => 'courses#input', :as => :course_input
  get '/:transaction_type/course/show' => 'courses#show', :as => :show_courses
  post '/:transaction_type/course/find' => 'courses#find', :as => :find_course
  get '/:transaction_type/courses/:id/book/show' => 'courses#show_books', :as => :show_books
  get '/courses/:id/book/new' => 'books#display_new', :as => :display_new_book
  put '/courses/:id/book/new' => 'books#create_new', :as => :create_new_book
  get '/books/:book_id/posting/show' => 'books#show_postings', :as => :show_postings
  get '/books/:book_id/posting/new' => 'postings#display_new', :as => :display_new_posting
  put '/books/:book_id/posting/new' => 'postings#create_new', :as => :create_new_posting
  get '/postings/:posting_id' => 'postings#show', :as => :show_posting
  post '/postings/:posting_id' => 'postings#commit_buy', :as => :commit_buy_posting
  get '/course/find_course_numbers' => 'courses#find_course_numbers', :as => :find_course_numbers
  get '/course/find_course_sections' => 'courses#find_course_sections', :as => :find_course_sections
  get '/postings/admin/:unique_string' => 'postings#admin', :as => :display_admin_posting
  post '/postings/admin/:unique_string' => 'postings#commit_edit_and_republish', :as => :commit_admin_posting
  delete '/postings/delete/:unique_string' => 'postings#delete', :as => :delete_posting
  get '/admin' => 'misc#display', :as => :display_admin_page
  post '/admin' => 'misc#commit_edit', :as => :commit_admin_page_edit
  put '/admin/addnew' => 'users#new', :as => :new_user
  match '/auth/:provider/callback', :to => 'sessions#create', :as => :login
  match '/auth/failure', :to => 'sessions#failure'
  get '/logout', :to => 'sessions#destroy', :as => :logout
  
  get '/admin/fake_login' => 'users#fake_login', :as => :fake_login

end

app/models/misc.rb
class Misc < ActiveRecord::Base
  validates :key, :uniqueness => true
end

app/controllers/misc_controller.rb
class MiscController < ApplicationController

  def display
    if session[:user_id].nil?
      redirect_to "/auth/facebook" and return
    end
    @semester = Misc.find_by_key("semester").value
    @year = Misc.find_by_key("year").value
    @expiration_time = Misc.find_by_key("expiration_time").value
  end

  def commit_edit
    if session[:user_id].nil?
      flash[:warning] = "You do not have privileges to update these values."
      redirect_to index_path() and return
    end
    if params[:misc][:expiration_time] =~ /^\d+$/
      expiration = Misc.find_by_key("expiration_time")
      expiration.value = params[:misc][:expiration_time].to_s
      expiration.save
    end
    new_semester = params[:misc][:semester]
    new_year = params[:misc][:year]
    old_semester = Misc.find_by_key("semester").value
    old_year = Misc.find_by_key("year").value
    time = Time.new
    if new_semester != old_semester or (new_year != old_year and new_year.to_i >= time.year and new_year.to_i <= time.year + 1.year)
      if new_semester != old_semester
        misc = Misc.find_by_key("semester")
        misc.value = new_semester
        misc.save
      end
      if new_year != old_year and new_year.to_i >= time.year and new_year.to_i <= time.year + 1.year
        misc = Misc.find_by_key("year")
        misc.value = new_year.to_s
        misc.save
      end
      Course.get_courses_for(Misc.find_by_key("semester").value, Misc.find_by_key("year").value)
      Book.get_books()
    end
    flash[:notice] = "Settings Saved!"
    redirect_to display_admin_page_path()
  end
  
end

app/views/misc/display.html.haml
%h2 Admin page

= form_tag commit_admin_page_edit_path, :method => :post, :id => "admin_control_form" do

	%p
		= label :misc, :expiration_time, "Posting Expiration Time"
		%br
		= text_field :misc, :expiration_time, :value => "#{@expiration_time}", :id => "expiration_time", :class => "required integer_field"
	
	%p
		= label :misc, :year, "Current Year"
		%br
		= text_field :misc, :year, :value => "#{@year}", :id => "year", :class => "required integer_field"
		
	%p
		= label :misc, :semester, "Current Semester"
		%br
		= select :misc, :semester, ['spring', 'fall', 'summer'], :value => "#{@semester}" 
    
	%p
		= submit_tag "Update"
		
%br
		
= form_tag new_user_path, :method => :put, :id => "add_admin_form" do

	= label :user, :email, "New Admin User (Facebook e-mail):"
	%br
	= text_field :user, :email, :class => "required email"
	%br  
	= submit_tag "Add new Admin user"

%br

= button_to "Log Out", logout_path(), :method => :get