config/routes.rb
Textbookswap::Application.routes.draw do

  match '/' => 'index#index', :as => :index
  get '/admin/courses/input/:term/:year' => 'courses#input', :as => :course_input
  get '/:transaction_type/course/show' => 'courses#show', :as => :show_courses
  post '/:transaction_type/course/find' => 'courses#find', :as => :find_course
  get '/:transaction_type/courses/:id/book/show' => 'courses#show_books', :as => :show_books
  get '/courses/:id/book/new' => 'books#display_new', :as => :display_new_book
  put '/courses/:id/book/new' => 'books#create_new', :as => :create_new_book
  get '/books/:book_id/posting/show' => 'books#show_postings', :as => :show_postings
  get '/books/:book_id/posting/new' => 'postings#display_new', :as => :display_new_posting
  put '/books/:book_id/posting/new' => 'postings#create_new', :as => :create_new_posting
  get '/postings/:posting_id' => 'postings#show', :as => :show_posting
  post '/postings/:posting_id' => 'postings#commit_buy', :as => :commit_buy_posting
  get '/course/find_course_numbers' => 'courses#find_course_numbers', :as => :find_course_numbers
  get '/course/find_course_sections' => 'courses#find_course_sections', :as => :find_course_sections
  get '/postings/admin/:unique_string' => 'postings#admin', :as => :display_admin_posting
  post '/postings/admin/:unique_string' => 'postings#commit_edit_and_republish', :as => :commit_admin_posting
  delete '/postings/delete/:unique_string' => 'postings#delete', :as => :delete_posting
  get '/admin' => 'misc#display', :as => :display_admin_page
  post '/admin' => 'misc#commit_edit', :as => :commit_admin_page_edit
  put '/admin/addnew' => 'users#new', :as => :new_user
  match '/auth/:provider/callback', :to => 'sessions#create', :as => :login
  match '/auth/failure', :to => 'sessions#failure'
  get '/logout', :to => 'sessions#destroy', :as => :logout
  
  get '/admin/fake_login' => 'users#fake_login', :as => :fake_login

end

app/views/layouts/application.html.haml
%html

	%head
	
		%title TextBook Swap!
		= stylesheet_link_tag 'application'
		= javascript_include_tag 'application'
		= csrf_meta_tags
	
	%body
	
		- if not session[:user_id].nil?
			#admin
				Logged in as Admin
				
		#sign
			= link_to image_tag('logo.png', :size =>'300x45'), '/'
			
		#wrapper
		
			- if flash[:notice]
				#notice.message= flash[:notice]
			- elsif flash[:warning]
				#warning.message= flash[:warning]
				
			= yield
			
			#footer
				Copyright © 2012 CS169SP12G15 
				|
				- if not session[:user_id].nil?
					= link_to "Admin Page", display_admin_page_path()
				- else
					= link_to "Admin Login", display_admin_page_path()

app/views/layouts/home.html.haml
%html

  %head
  
    %title TextBook Swap!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  
  #wrapper
      
    #sign
      = link_to image_tag('logo.png', :size =>'300x45'), '/'
      
    = yield